### ISSUE TITLE
有使用的例子吗? 很感兴趣

### ISSUE THREAD

**Issue by gopkg-dev** [go-saas/saas#1]

**Comment by goxiaoy** [comment]
如果你用的web框架gin ，请看 https://github.com/Goxiaoy/go-saas/blob/main/gin/middleware/multi_tenantcy_test.go
如果你用的orm框架gorm，请看https://github.com/Goxiaoy/go-saas/blob/main/management/gorm/sqlite_db_test.go

其他的我现在在做其他事情，还不支持。
理论上任何支持Middleware的web框架都可以套用，任何数据库连接方法都支持Single-tenancy模式，任何支持全局filter的orm都会支持Hybrid tenancy models

我曾经想把一个现有的 admin系统改成saas， https://github.com/Goxiaoy/gin-vue-admin ，但是发现他设计的时候权限不是很兼容Hybrid tenancy models，只能每个租户独享一个数据库，不能公用一个数据库，就没有继续下去了

具体设计可以看wiki  https://github.com/Goxiaoy/go-saas/wiki

**Comment by goxiaoy** [comment]
单体： https://github.com/Goxiaoy/go-saas/tree/main/examples
微服务： https://github.com/Goxiaoy/go-saas-kit
