### ISSUE TITLE
dockerized version

### ISSUE THREAD

**Issue by ghost** [go-saas/saas#2]
Hi @Goxiaoy ,

Hope you are all well !

I was wondering if you can bundle go-saas backend and frontend into a docker-compose file ? I would like to have a try.

Cheers,
Luc Michalski

**Comment by goxiaoy** [comment]
Hi @lucmichalski 
At the beginning, this project targets to provider a headless solution for developers to fit their own developing stack, so it's not an end-to-end solution like https://github.com/thedevdojo/wave. There are so many choices to develop end-to-end services, such as different front-end, different web frameworks, different database access layer, and I do not want to set a limitation for someone interesting in delivering saas.
The codes are a portable version from our business, and I want to demonstrate a way to turn a existing software into saas mode.

But I am willing to open source more codes from our project which includes frontend (Vue), and sorry there is no time estimation

Best.
G

**Comment by goxiaoy** [comment]
https://github.com/Goxiaoy/go-saas-kit/issues/4

**Comment by goxiaoy** [comment]
Headless example https://github.com/Goxiaoy/go-saas/tree/main/examples
