### ISSUE TITLE
可以写一个mysql的使用案例吗

### ISSUE THREAD

**Issue by Qiufcong** [go-saas/saas#5]
你好，我是个刚入门的golang ,你能写一个mysql的使用案例吗,我找了好久的saas的租户独立库解决方案，我看到你这个，觉得是没问题的。现在也在一点一点看你的源码，我使用的技术是gin+gorm+mysql,如果你能写一个mysql的使用案例 可以给我很大的帮助，当然是你有空的时候。

**Comment by goxiaoy** [comment]
你先看看https://github.com/Goxiaoy/go-saas/tree/main/gorm 这个下面的test文件吧。后续有应该有更多的开源内容，但是还没有时间规划。

**Comment by goxiaoy** [comment]
https://github.com/Goxiaoy/go-saas/blob/7fab63a5af76a698eb89199d351d52e632f0c1e5/examples/example.go#L23-L26

**Comment by ppusapati** [comment]
Any minimalistic example with Postgres or MySQL would be great
